repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
      - id: ruff-format

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      -   id: mypy
          files: ^src/
          args: [--strict]
          additional_dependencies: [pydantic, pydantic_settings, fastapi, sentry_sdk]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: detect-private-key
